### PR TITLE
INSLYPROD-7145/7163: Prepare client for multiple role user

### PR DESCRIPTION
**Pull request by taron-insly**
## TODO
- disable header X-Target from out IPs (in QMT side). Handle in Ingress level (whitelist VPN, Estonia and Poland IPs also)

INSLYPROD-7047
INSLYPROD-7163

### CODE REVIEW

**Comment by psafarov** [comment]
@taron-insly another feature we are missing is finding customer by domain

**Comment by taron-insly** [comment]
> @taron-insly another feature we are missing is finding customers and objects by domain

We dont have such possibility. 
Also why you need it?

**Comment by psafarov** [comment]
With a help of a workaround we can keep search by domain for later

**Comment by psafarov** [comment]
Merged in #11

**Pull request closed without merging**
